config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
    
   }
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
   
   
  get 'posts/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  resources :posts
  
  root 'home#top' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

has_many :posts


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
      before_action :configure_permitted_parameters, if: :devise_controller?

      protected

      def configure_permitted_parameters
        added_attrs = [ :email, :user_name, :password, :password_confirmation ]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :set_post, only: [:show, :edit, :update, :destroy]





  def index
    @posts=Post.all
  end
  
  
  def show
    @post=Post.find_by(id: params[:id])
  end
  
  
  
  def new
  
  if !current_user
    redirect_to new_user_session_path
  else
    @post=Post.new
  end
 
  end
  
  
  
  def edit
    if @post.user != current_user
        redirect_to post_path(@post)
    end
  end
  
 
  
  
  
  
  def create
  @post = Post.new(post_params)
  @post.user_id = current_user.id
  respond_to do |format|
    if @post.save
      format.html { redirect_to @post, notice: 'Post was successfully created.' }
      format.json { render :show, status: :created, location: @post }
    else
      format.html { render :new }
      format.json { render json: @post.errors, status: :unprocessable_entity }
    end
  end
end



 def update
   respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  
  
  def destroy
      if @post.user == current_user   
        @post.destroy
      end 
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end





private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title,:event_date,:application_deadline,:holding_area,:venue,:capacity,:cost,:age,:longtext)
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

   # DELETE /resource/sign_out
   def destroy
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/top.html.erb
<div class="main">

    <div class="top-wrapper">
        <h1>SoccerMatchで サッカーをより日常に</h1>
        <p>〜サッカーをもっと楽しむためのSNS〜</p>
        <a href="/posts" class="btn">募集一覧</a>
    </div>




    <div class="content-wrapper">


        <h4>SoccerMatchでできる3つのこと</h4>


        <div class="contents">

            <div class="content">
                <p>仲間を募集する</p>
                <i class="fas fa-users icon"></i>
            </div>

            <div class="content">
                <p>試合に参加する</p>
                <i class="fas fa-futbol icon"></i>
            </div>


            <div class="content">
                <p>試合を組む</p>
                <i class="far fa-handshake icon"></i>
            </div>


        </div>

    </div>











    <div class="home-field-wrapper">



        <div class="container">

            <h3>Field</h3>


            <div class="home-fields">

                <div class="home-field">

                    <h4>サッカー</h4>

                    <p class="home-field-content">
                        現在サッカーは、200を越える国と地域で、2億5千万人を超える選手達によってプレーされており、4年に一度行われるFIFAワールドカップのテレビ視聴者数は全世界で通算300億人を超えており、世界で最も人気のあるスポーツと言われている。
                    </p>
                </div>

                <div class="home-field">

                    <h4>ソサイチ</h4>

                    <p class="home-field-content">
                        ブラジルでは、ソサイチと呼ばれ、
                        サッカーコートの1/4サイズ、GKを含め7人対7人の人数で行われ、男女共にジュニアの育成年代からシニアまでの生涯スポーツとして、さらには競技（リーグ・国際大会など)としても盛んに行われている。
                    </p>
                </div>


                <div class="home-field">

                    <h4>フットサル</h4>

                    <p class="home-field-content">5対5のミニサッカー。25〜42×15〜22mのコートで行われ、ゴールサイズも2×3m。南米ではサロン・フットボールと呼ばれる弾まないボールを使っての室内サッカーが盛んに行われている。</p>
                </div>



            </div>
        </div>


        <div class="contents2">

        </div>

    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoccerMatchNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


      <header>


          <div class="header-logo">
              <h4><a href="/">SoccerMatch</a></h4>
          </div>
          <ul class="header-menu">
              <li><a href="/posts/index">募集一覧</a></li>
              <li><a href="/posts/new">募集したい</a></li>
              <% if user_signed_in? %>
                <li><a href="/users/sign_out">Logout</a></li>
              <% else %>
              <li><a href="/users/sign_up">Sign Up</a></li>
              <li><a href="/users/sign_in">Login</a></li>
              <% end %>

          </ul>
      </header>

     

      <%= yield %>


      <footer>
          <div class="footer-logo">
              <h4><a href="/home/top">SoccerMatch</a></h4>
          </div>
          <ul class="footer-menu">
              <li><a href="#">募集一覧</a></li>
              <li><a href="#">募集したい</a></li>
              <li><a href="#">Sign Up</a></li>
              <li><a href="#">Login</a></li>
          </ul>
      </footer>



  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>

<div class="apply-create">



    <div class="apply-header">

        <h4>募集情報の新規作成</h4>

    </div>


    <div class="apply-forms">


        <div class="apply-form">
            <%= form.label :分野 %>
            <%= form.select :field, [["サッカー","サッカー"],["ソサイチ","ソサイチ"],["フットサル","フットサル"]],id: :post_field %>
        </div>


        <div class="apply-form">
            <%= form.label :タイトル %>
            <%= form.text_field :title, id: :post_title %>
        </div>

        <div class="apply-form">
            <%= form.label :開催日 %>
            <%= form.date_field :event_date, id: :event_date %>
        </div>

        <div class="apply-form">
            <%= form.label :募集期限 %>
            <%= form.date_field  :application_deadline, id: :post_applicationdeadline %>
        </div>

        <div class="apply-form">
            <%= form.label :開催エリア %>
            <%= form.select :holding_area,[["北海道","北海道"],["青森","青森"],["岩手","岩手"],["宮城","宮城"],["秋田","秋田"],["山形","山形"],["福島","福島"],["茨城","茨城"],["栃木","栃木"],["群馬","群馬"],["埼玉","埼玉"],["千葉","千葉"],["東京","東京"],["神奈川","神奈川"],["新潟","新潟"],["富山","富山"],["石川","石川"],["福井","福井"],["山梨","山梨"],["長野","長野"],["岐阜","岐阜"],["静岡","静岡"],["愛知","愛知"],["三重","三重"],["滋賀","滋賀"],["京都","京都"],["大阪","大阪"],["奈良","奈良"],["和歌山","和歌山"],["鳥取","鳥取"],["島根","島根"],["岡山","岡山"],["広島","広島"],["山口","山口"],["徳島","徳島"],["香川","香川"],["愛媛","愛媛"],["高知","高知"],["福岡","福岡"],["佐賀","佐賀"],["長崎","長崎"],["熊本","熊本"],["大分","大分"],["宮崎","宮崎"],["鹿児島","鹿児島"],["沖縄","沖縄"]],id: :post_holding_area %>
        </div>

        <div class="apply-form">
            <%= form.label :会場 %>
            <%= form.text_field :venue, id: :post_venue  %>
        </div>

        <div class="apply-form">
            <%= form.label :定員 %>
            <%= form.number_field :capacity, id: :post_capacity %>人
        </div>

        <div class="apply-form">
            <%= form.label :費用 %>
            <%= form.number_field :cost, id: :post_cost %>円
        </div>

        <div class="apply-form">
            <%= form.label :年代 %>
            <%= form.select :age, [["指定なし","指定なし"],["10代","10代"],["20代","20代"],["30代","30代"],["40代","40代"],["50代","50代"],["60歳以上","60歳以上"]],id: :post_age %>
        </div>

        <div class="apply-form">
            <%= form.label :コメント %>
            <%= form.text_area :comment, id: :comment  %>
        </div>




        <div class="actions">
            <%= form.submit %>
        </div>


    </div>





</div>

<% end %>

app/views/posts/edit.html.erb

<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="index-body-wrapper">




    <h3>募集情報一覧</h3>



    <ul class="posts-lists">



        <% @posts.each do |post| %>

        <li class="posts-list">

            <div class="posts-title">
                <h4><%= link_to(post.title, post) %></h4>
            </div>

            <div class="posts-info">

                <p>分野:<%= post.field %></p>
                <p>開催日:<%= post.event_date %></p>
                <p>開催地:<%= post.venue%></p>


                <p>定員:<%= post.capacity %>人</p>
                <p>費用:<%= post.cost %>円</p>

            </div>

            <% if post.user == current_user %>
                <%= link_to '編集', edit_post_path(post) %> |
                <%= link_to '削除', post, method: :delete, data: { confirm: '本当によろしいですか' } %>
            <% end %>

        </li>

        <br>

        <%end%>



    </ul>


</div>

app/views/posts/new.html.erb
<div class="form">
    <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="show-wrapper">


    <div class="post-show-item">
        <h4><%= @post.title %></h4>
        <a href=" " class="apply-btn">応募する</a>

        <div class="post-show-info">

            <p>募集者：</p>
            <p>開催日：<%= @post.event_date %></p>
            <p>応募締め切り：<%= @post.application_deadline %></p>
            <p>開催地：<%= @post.holding_area %></p>
            <p>会場：<%= @post.venue %></p>
            <p>定員：<%= @post.capacity %>人</p>
            <p>費用：<%= @post.cost %>円</p>
            <p>年代：<%= @post.age %></p>
            <p>コメント：<%= @post.comment %></p>

        </div>

    </div>


    <% if  @post.user == current_user %>
        <%= link_to '編集', edit_post_path(@post) %> |
    <% end %>
    <%= link_to '戻る', posts_path %>


</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワード忘れた方はこちら", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>